### ISSUE TITLE
chore(codeowners): setup codeowners

### ISSUE THREAD

**Issue by Zaba505** [z5labs/megamind#48]
Create CODEOWNERS file with at least the following assignments:
- @erictg should be responsible for any k8s yaml config/terraform
- @Zaba505 should be responsible for any bazel config

**Comment by nikitawootten** [comment]
Rather then specify specific people, I'll delegate ownership to teams of z5labs (infrastructure team, build team, etc...)

**Comment by Zaba505** [comment]
Let me know if you don't have permission to create the teams and I'll help you create them or just give you permission to create them.

**Comment by Zaba505** [comment]
implemented by: #69
